site_name: Knative Docs
site_url: https://knative.dev/docs
site_description: Knative Documentation

repo_url: https://github.com/knative/docs
edit_uri: edit/main/docs

nav:
    - Home: index.md
    - Installing Knative:
        - Overview: install/index.md
        - Installing using YAML: install/any-kubernetes-cluster.md
        - Installing with the Operator: install/knative-with-operators.md
        - Using a Knative-based Offering: install/knative-offerings.md
    - Serving Component:
        - Getting Started: serving/getting-started-knative-app.md
        - Knative Services: 
          - Creating Knative Services: serving/services/creating-services.md
          - Configuring the Knative Deployment: serving/services/deployment.md
        - Knative Kubernetes Components: serving/knative-kubernetes-services.md
        - Using a Private Registry: serving/deploying/private-registry.md
        - Accessing Request Traces: serving/accessing-traces.md
        - Configuing Cluster-Local Services: serving/cluster-local-route.md
        - Creating and Using Sub-Routes: serving/using-subroutes.md
        - Gradually Rolling out Revisions: serving/rolling-out-latest-revision.md
        - Debugging Issues with your Application: serving/debugging-application-issues.md
        - Enabling tag to digest resolution: serving/tag-resolution.md 
        - Configuring high-availability components: serving/config-ha.md
        - Feature Flags: serving/feature-flags.md
        - Configuring HTTPS Connections: serving/using-a-tls-cert.md
        - Setting up Cert-Manager:
          - Installing cert-manager for TLS Certificates: serving/installing-cert-manager.md
          - Configuring HTTPS with cert-manager and Google Cloud DNS: serving//using-cert-manager-on-gcp.md
          - Enabling automatic TLS certificate provisioning: serving/using-auto-tls.md
        - Exclude namespaces from the Knative webhook: serving/webhook-customizations.md
        - GKE-Specific Customization:
          - Assigning Static IPs in GKE: serving/gke-assigning-static-ip-address.md
          - Using ExternalDNS on Google Cloud Platform to automate DNS setup: serving/using-external-dns-on-gcp.md
        - Custom Domains:
          - Setting up a Custom Domain: serving/using-a-custom-domain.md
          - Setting up a Custom Domain per Service: serving/using-a-custom-domain-per-service.md
          - Creating Domain Mappings: serving/creating-domain-mappings.md
        - Using Knative Load Balancing: 
          - Overview: serving/load-balancing/index.md
          - Target Burst Capacity: serving/load-balancing/target-burst-capacity.md
        - Istio-Specific Configuration:
          - Setting up custom ingress gateway: serving/setting-up-custom-ingress-gateway.md
          - Enabling requests to Knative services when additional authorization policies are enabled: serving/istio-authorization.md
        - Autoscaling: 
          - Overview: serving/autoscaling/README.md
          - Concepts: serving/autoscaling/autoscaling-concepts.md
          - Metrics: serving/autoscaling/autoscaling-metrics.md
          - Targets: serving/autoscaling/autoscaling-targets.md
          - Configuring Scale-to-zero: serving/autoscaling/scale-to-zero.md
          - Configuring Concurrency: serving/autoscaling/concurrency.md
          - Configuring Scale Bounds: serving/autoscaling/scale-bounds.md
          - Configuring RPS Target: serving/autoscaling/rps-target.md
          - KPA-Specific Configuration: serving/autoscaling/kpa-specific.md
          - Autoscaling Sample App: serving/autoscaling/autoscale-go/README.md
        - Samples:
          - Overview: serving/samples/README.md
          - Hello World:
            - Hello World Go: serving/samples/hello-world/helloworld-go/index.md
          - Rest API: serving/samples/rest-api-go/README.md
          - Cloud Events:
            - NodeJS: serving/samples/cloudevents/cloudevents-nodejs/README.md
            - Java (Vert.x): serving/samples/cloudevents/cloudevents-vertx/README.md
            - Rust: serving/samples/cloudevents/cloudevents-rust/index.md
          - Blue Green Deployment: serving/samples/blue-green-deployment.md
    - Eventing Component:
        - Samples: eventing/samples.md
    - Client:
        - Installing the Client: client/install-kn.md
        - Using the Client: client/_index.md
    - Reference: 
      - Serving: reference/api/serving.md
      - Eventing: reference/api/eventing/eventing.md
    - Community: todo

theme:
  name: material
  logo: images/logo/rgb/knative-logo-rgb.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - toc.integrate

plugins:
  - search
  - macros

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - admonition
  - toc:
      permalink: true

extra:
  version: v0.21.0
