name: Publish MkDocs

on:
  push:
    branches: [ gh-pages-blog ]

jobs:
  mkdocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.83.1'

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-macros-plugin mkdocs-exclude mike
          npm install
      
      - name: Build docs 
        run: |
          ./hack/build-with-blog.sh 

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          user_name: Knative Automation'
          user_email: automation@knative.team

